### PR TITLE
remove alert

### PR DESCRIPTION
**Pull request by adarsh-dhakad**
i remove unnecessary code

### CODE REVIEW

**Review by sudama011 — APPROVED** [review]
good work

**Comment by adarsh-dhakad** [comment]
hello i update readme file

**Comment by adarsh-dhakad** [comment]
Please accept

**Review by adarsh-dhakad — COMMENTED** [review]
okay

**Review by sudama011 — APPROVED** [review]
good job

**Review by adarsh-dhakad — COMMENTED** [review]
w

**Pull request closed without merging**
